# Generated by Django 5.1 on 2024-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=20)),
                ("profilePic", models.BinaryField()),
                ("permissionLevel", models.IntegerField()),
                ("mail", models.EmailField(max_length=254)),
                ("userid", models.UUIDField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("nickname", models.CharField(max_length=50)),
                ("bio", models.TextField()),
                (
                    "bloodGroup",
                    models.TextField(
                        choices=[
                            ("o+", "O Positive"),
                            ("o-", "O Negative"),
                            ("ab+", "Ab Positive"),
                            ("ab-", "Ab Negative"),
                            ("a+", "A Positive"),
                            ("a-", "A Negative"),
                            ("b+", "B Positive"),
                            ("b-", "B Negative"),
                        ]
                    ),
                ),
            ],
        ),
    ]
