# Generated by Django 5.1 on 2024-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userid",
            new_name="userId",
        ),
    ]
