# Generated by Django 5.1 on 2024-08-14 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0003_user_createdat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="mail",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="profilePic",
            new_name="profilePicture",
        ),
    ]
