# Generated by Django 5.1 on 2024-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0004_rename_mail_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePicture",
            field=models.BinaryField(editable=True),
        ),
    ]
