# Generated by Django 5.1 on 2024-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0005_alter_user_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePicture",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
