# Generated by Django 5.1 on 2024-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0007_remove_user_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.UUIDField(auto_created=True),
        ),
    ]
