# Generated by Django 5.1 on 2024-08-15 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0009_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
