# Generated by Django 5.1 on 2024-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0010_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bloodGroup",
            field=models.TextField(
                choices=[
                    ("NOTA", "Not Available"),
                    ("o+", "O Positive"),
                    ("o-", "O Negative"),
                    ("ab+", "Ab Positive"),
                    ("ab-", "Ab Negative"),
                    ("a+", "A Positive"),
                    ("a-", "A Negative"),
                    ("b+", "B Positive"),
                    ("b-", "B Negative"),
                ]
            ),
        ),
    ]
